// Generated by https://quicktype.io

export interface Pokemon {
  base_experience: number;
  height: number;
  id: number;
  name: string;
  order: number;
  sprites: {
    front_default: string;
  };
  weight: number;
}
